name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERSION: 0.1.19
    steps:
      - uses: actions/checkout@v2
      - name: test workdir
        run: |
          ls -al
          ls -al ..
          pwd
      - name: build docker image
        run: sudo docker build . --build-arg JAR_FILE=target/wca-ds-${VERSION}.jar --tag lzbot/wca-data-service:latest --tag lzbot/wca-data-service:${VERSION}
      - name: push docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sudo docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
          sudo docker push hub.docker.com/lzbot/wca-data-service:${VERSION}
          sudo docker push hub.docker.com/lzbot/wca-data-service:latest

